# Generated by Django 5.2.8 on 2025-12-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_fundraiser_date_created_fundraiser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
