# Generated by Django 5.2.8 on 2026-02-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0004_alter_fundraiser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
